Update CHANGELOG.md for patch release
rancher/terraform-provider-rke pull request #344
Opened 2022-05-25 19:56 UTC by annablender

2022-05-25 20:15 UTC, paynejacob requested changes

2022-05-25 20:15 UTC, paynejacob commented on CHANGELOG.md
> +FEATURES:
We can drop the empty sections

2022-05-25 20:15 UTC, paynejacob commented on CHANGELOG.md
> +## 1.3.1 (May 25, 2021)
```suggestion
## 1.3.1 (May 25, 2022)
```

2022-05-25 20:15 UTC, paynejacob commented on CHANGELOG.md
> +* Patch & re-assign `rke_cluster_yaml` post create. See https://github.com/rancher/terraform-provider-rke/pull/327
```suggestion
* Patch & re-assign `rke_cluster_yaml` post create. See [#327](https://github.com/rancher/terraform-provider-rke/pull/327)
```

2022-05-25 21:34 UTC, paynejacob approved these changes

2022-05-25 21:36 UTC, snasovich approved these changes

2022-05-25 21:37 UTC, snasovich commented
@annablender , this is ready to be merged now and you can just create v1.3.1 in GH Releases using the release notes we've reviewed here.

2022-05-25 22:09 UTC, merged

2022-06-27 23:58 UTC, Patricol commented
Do we know when a release will be created?

I've been waiting on this for a few months.

Thanks for all the great work!

2022-06-28 01:53 UTC, snasovich commented
@Patricol , unfortunately we're still blocked by an issue on Hashicorp's side per https://github.com/rancher/terraform-provider-rke/issues/346#issuecomment-1164513836. I'm going to ping them again and see if there is any update.